import type { Metadata } from 'next'
import './globalStyles/normalize.css'
import './globalStyles/globals.css'
import '@/app/globalStyles/header.css'
import '@/app/globalStyles/menu.css'
import '@/app/globalStyles/mobile-navbar.css'
import '@/app/globalStyles/catalog-menu.css'
import '@/app/globalStyles/search-modal.css'
import '@/app/globalStyles/cart-popup.css'
import '@/app/globalStyles/footer.css'
import '@/app/globalStyles/slick.css'
import '@/app/globalStyles/slick-theme.css'
import PagesLayout from '@/components/layouts/PagesLayout'

export const metadata: Metadata = {
  title: 'Archibais',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return <PagesLayout>{children}</PagesLayout>
}
